# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-builtin-literals
  - id: double-quote-string-fixer
  - id: fix-encoding-pragma
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.32.0
  hooks:
  - id: yapf
    additional_dependencies: [toml]
- repo: https://github.com/hadialqattan/pycln
  rev: v1.3.3
  hooks:
  - id: pycln
    args: [--config=pycln.toml]
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
# - repo: https://github.com/jazzband/pip-tools
#   rev: 6.2.0
#   hooks:
#     - id: pip-compile
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v1.3.0
  hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
