version: 2.1

orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.2
  sonarcloud: sonarsource/sonarcloud@1.0.2

workflows:
  test:  # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
    jobs:
      - test:
          context: SonarCloud
          filters:
            tags:
              # see https://circleci.com/docs/2.0/configuration-reference/#tags
              ignore: /.*/
      - deploy:
          context: SonarCloud
          filters:
            # only run for the official tags
            tags:
              only: /v.*/
            # deploy only tags, not branches
            branches:
              ignore: /.*/

notify:
  webhooks:
    # gitter notifications
    - url: https://webhooks.gitter.im/e/16634961392360db480a

jobs:
  test:
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true # Specified using docker layer caching, but it is only available for Performance Plan.
    resource_class: medium
    steps:
        - checkout
        - run: |
            changes=`git show --name-only ${CIRCLE_SHA1} | tail -n +7`

            if [ "$changes" = ".circleci/config.yml" ]; then
              echo "Only found a configuration change. Stopping build"
              circleci-agent step halt
            fi
        - run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.12/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
        - run: earthly --secret SONAR_TOKEN="${SONAR_TOKEN}" --ci +sanity-check
  deploy:
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true # Specified using docker layer caching, but it is only available for Performance Plan.
    resource_class: medium
    steps:
        - checkout
        - run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.12/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
        - run: earthly --secret SONAR_TOKEN="${SONAR_TOKEN}" --secret pypi-username="clk_uploader" --secret pypi-password="${PYPI_PASSWORD}" --ci --push +deploy
